<?php
$pageTitle = 'Log in — RJM Boardinghouse';
$error = $error ?? null;
$lastEmail = $_SESSION['flash_email'] ?? '';
unset($_SESSION['flash_email']);
$qrToken = $qrToken ?? null;
$qrLoginUrl = $qrLoginUrl ?? '/login';
$defaultMobileUrl = $defaultMobileUrl ?? 'http://127.0.0.1:8000/login';

ob_start();
?>

<!-- Custom Animista Ken Burns Animation & Glassmorphic Modal Styles -->
<style>
/* ----------------------------------------------
 * Generated by Animista on 2026-9-12 18:26:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-top
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-top {
  0% {
    -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 16%;
            transform-origin: 50% 16%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(-15px);
            transform: scale(1.25) translateY(-15px);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
}
@keyframes kenburns-top {
  0% {
    -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 16%;
            transform-origin: 50% 16%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(-15px);
            transform: scale(1.25) translateY(-15px);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
}

.kenburns-top-bg {
    -webkit-animation: kenburns-top 24s cubic-bezier(0.250, 0.460, 0.450, 0.940) infinite alternate both;
            animation: kenburns-top 24s cubic-bezier(0.250, 0.460, 0.450, 0.940) infinite alternate both;
}

@media (prefers-reduced-motion: reduce) {
    .kenburns-top-bg {
        -webkit-animation: none !important;
                animation: none !important;
    }
}

/* Landing background container */
.landing-bg-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    overflow: hidden;
    z-index: 0;
}

.landing-bg-image {
    position: absolute;
    top: -5%;
    left: -5%;
    width: 110%;
    height: 110%;
    background-image: url('/assets/images/landing-bg.jpg');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
}

.landing-bg-overlay {
    position: absolute;
    inset: 0;
    background: radial-gradient(circle at center, rgba(15, 23, 42, 0.55) 0%, rgba(15, 23, 42, 0.85) 100%);
    backdrop-filter: blur(3px);
    -webkit-backdrop-filter: blur(3px);
}

/* Outer Frosted Halo matching reference design */
.modal-halo-container {
    background: rgba(255, 255, 255, 0.18);
    backdrop-filter: blur(20px);
    -webkit-backdrop-filter: blur(20px);
    padding: 10px;
    border-radius: 2rem;
    border: 1px solid rgba(255, 255, 255, 0.35);
    box-shadow: 0 35px 70px -15px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.15);
    width: 100%;
    max-width: 960px;
    transition: transform 0.25s ease, box-shadow 0.25s ease;
}

/* Inner Pure White Card */
.modal-inner-card {
    background: #ffffff;
    border-radius: 1.625rem;
    overflow: hidden;
    box-shadow: 0 4px 25px rgba(15, 23, 42, 0.08);
}

/* Outline Social/Role Login Buttons matching reference */
.social-outline-btn {
    width: 100%;
    height: 2.625rem;
    border: 1px solid #e2e8f0;
    border-radius: 0.5rem;
    background: #ffffff;
    color: #334155;
    font-size: 0.8125rem;
    font-weight: 500;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.625rem;
    cursor: pointer;
    transition: all 140ms ease;
    text-decoration: none;
}

.social-outline-btn:hover {
    background: #f8fafc;
    border-color: #cbd5e1;
    color: #0f172a;
    transform: translateY(-1px);
    box-shadow: 0 2px 4px rgba(15, 23, 42, 0.04);
}

.social-outline-btn:active {
    transform: translateY(0);
}

/* Blue Primary Button matching reference */
.btn-ref-primary {
    width: 100%;
    height: 2.75rem;
    background: #1d4ed8;
    color: #ffffff;
    font-size: 0.875rem;
    font-weight: 600;
    border-radius: 0.5rem;
    border: none;
    cursor: pointer;
    transition: background-color 140ms ease, box-shadow 140ms ease, transform 140ms ease;
    box-shadow: 0 1px 2px rgba(29, 78, 216, 0.2);
}

.btn-ref-primary:hover {
    background: #1e40af;
    box-shadow: 0 4px 12px rgba(29, 78, 216, 0.35);
    transform: translateY(-1px);
}

.btn-ref-primary:active {
    background: #172554;
    transform: translateY(0);
}

/* Input Styles matching reference */
.ref-input {
    width: 100%;
    height: 2.625rem;
    border: 1px solid #d1d5db;
    border-radius: 0.5rem;
    padding: 0 0.875rem;
    font-size: 0.875rem;
    color: #111827;
    background: #ffffff;
    transition: border-color 140ms ease, box-shadow 140ms ease;
}

.ref-input:focus {
    outline: none;
    border-color: #2563eb;
    box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.15);
}

.ref-input.border-error {
    border-color: #ef4444;
}

.ref-input.border-error:focus {
    box-shadow: 0 0 0 3px rgba(239, 68, 68, 0.15);
}

.password-field-wrap {
    position: relative;
    width: 100%;
}

.password-field-wrap .ref-input {
    padding-right: 2.5rem;
}

.password-toggle {
    position: absolute;
    top: 50%;
    right: 0.5rem;
    transform: translateY(-50%);
    width: 1.75rem;
    height: 1.75rem;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0;
    margin: 0;
    border: none;
    background: transparent;
    color: #94a3b8;
    cursor: pointer;
    z-index: 2;
}

.password-toggle:hover {
    color: #475569;
}

.login-or-divider {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    padding: 1rem 0;
}

.login-or-divider .or-line {
    flex: 1 1 0%;
    border-top: 1px solid #e5e5e5;
}

.login-or-divider > span {
    flex: 0 0 auto;
    margin-left: 0.75rem;
    margin-right: 0.75rem;
    text-align: center;
}

#copy-feedback {
    opacity: 0;
    min-height: 1rem;
    display: block;
    transition: opacity 160ms ease;
}
#copy-feedback.is-visible {
    opacity: 1;
}

#qr-live-status {
    min-height: 1.25rem;
}
#qrcode-target img,
#qrcode-target canvas {
    margin: 0 auto;
    border-radius: 0.5rem;
}
</style>

<!-- Fullscreen Ken Burns Animated Background Layer -->
<div class="landing-bg-container" aria-hidden="true">
    <div class="landing-bg-image kenburns-top-bg"></div>
    <div class="landing-bg-overlay"></div>
</div>

<!-- Centered Landing Page Modal Viewport -->
<div class="relative z-10 min-h-screen flex items-center justify-center p-4 sm:p-6 lg:p-8" style="margin-bottom: -2.5rem;">

    <!-- Outer Translucent Frosted Halo (Matches Reference Image) -->
    <div class="modal-halo-container" id="login-modal-box">
        <div class="modal-inner-card">

            <!-- 2-Column Split: Left = Log In Form | Right = QR Code (Matches Reference Image) -->
            <div class="grid grid-cols-1 md:grid-cols-2">

                <!-- ======================================================= -->
                <!-- LEFT COLUMN: Log in Form                                -->
                <!-- ======================================================= -->
                <div class="p-8 sm:p-10 lg:p-11 flex flex-col justify-between" id="form-column">
                    <div>
                        <!-- Branding Accent Tag -->
                        <div class="flex items-center gap-2 mb-3">
                            <span class="w-6 h-6 rounded-md bg-amber-100 text-amber-700 flex items-center justify-center text-xs font-bold shadow-xs">
                                ▲
                            </span>
                            <span class="text-xs font-bold tracking-tight text-neutral-800 uppercase">
                                RJM Boardinghouse
                            </span>
                        </div>

                        <!-- Main Heading & Subtitle (Matches Reference Image) -->
                        <h1 class="text-3xl font-extrabold text-neutral-900 tracking-tight" style="font-size: 1.875rem; line-height: 1.2;">
                            Log in
                        </h1>
                        <p class="text-neutral-500 text-sm mt-1.5 mb-6">
                            We're so excited to see you again!
                        </p>

                        <?php if (!empty($error)): ?>
                            <div id="form-error-alert" class="bg-red-50 border border-red-200 text-red-700 text-xs rounded-lg px-3.5 py-2.5 mb-4 flex items-start gap-2" role="alert" aria-live="polite">
                                <span class="font-bold">⚠</span>
                                <span><?= htmlspecialchars($error) ?></span>
                            </div>
                        <?php endif; ?>

                        <!-- Standard Form Targeting /login -->
                        <form method="post" action="/login" id="login-form" class="space-y-4" autocomplete="on" novalidate>
                            <?= \App\Support\Csrf::field() ?>

                            <!-- Email Field -->
                            <div>
                                <label for="login-email" class="sr-only">Email</label>
                                <input id="login-email"
                                       type="email"
                                       name="email"
                                       required
                                       <?= empty($lastEmail) ? 'autofocus' : '' ?>
                                       autocomplete="email"
                                       value="<?= htmlspecialchars($lastEmail) ?>"
                                       placeholder="Email"
                                       class="ref-input"
                                       aria-describedby="email-error">
                                <p id="email-error" class="hidden text-xs text-red-600 mt-1" role="alert"></p>
                            </div>

                            <!-- Password Field with Show/Hide Toggle -->
                            <div>
                                <label for="login-password" class="sr-only">Password</label>
                                <div class="password-field-wrap">
                                    <input id="login-password"
                                           type="password"
                                           name="password"
                                           required
                                           <?= !empty($lastEmail) ? 'autofocus' : '' ?>
                                           autocomplete="current-password"
                                           placeholder="Password"
                                           class="ref-input <?= (!empty($error)) ? 'border-error' : '' ?>"
                                           aria-describedby="password-error">
                                    <button type="button"
                                            id="toggle-password"
                                            class="password-toggle"
                                            aria-label="Show password"
                                            title="Show / hide password"
                                            tabindex="0">
                                        <svg id="eye-open" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/></svg>
                                        <svg id="eye-closed" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="hidden" aria-hidden="true"><path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"/><path d="M14.084 14.158a3 3 0 0 1-4.242-4.242"/><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"/><path d="m2 2 20 20"/></svg>
                                    </button>
                                </div>
                                <p id="password-error" class="hidden text-xs text-red-600 mt-1" role="alert"></p>
                            </div>

                            <!-- Primary Blue Log in Button (Matches Reference Image) -->
                            <button type="submit" id="login-submit" class="btn-ref-primary">
                                Log in
                            </button>
                        </form>

                        <!-- "or" Divider (Matches Reference Image) -->
                        <div class="login-or-divider">
                            <div class="or-line"></div>
                            <span class="flex-shrink mx-3 text-xs text-neutral-400 font-medium">or</span>
                            <div class="or-line"></div>
                        </div>

                        <!-- 3 Quick Access Buttons (Matching Google/Facebook/Github style in reference) -->
                        <div class="space-y-2.5">
                            <button type="button"
                                    class="social-outline-btn quick-account-chip"
                                    data-email="admin@rjm.test"
                                    data-pass="AdminPass123!"
                                    title="Quick fill Admin test credentials">
                                <span class="text-sm">👑</span>
                                <span>Log in with Admin Account</span>
                            </button>

                            <button type="button"
                                    class="social-outline-btn quick-account-chip"
                                    data-email="staff@rjm.test"
                                    data-pass="StaffPass123!"
                                    title="Quick fill Staff test credentials">
                                <span class="text-sm">🔧</span>
                                <span>Log in with Staff Account</span>
                            </button>

                            <button type="button"
                                    class="social-outline-btn quick-account-chip"
                                    data-email="boarder@rjm.test"
                                    data-pass="BoarderPass123!"
                                    title="Quick fill Resident Boarder test credentials">
                                <span class="text-sm">🏠</span>
                                <span>Log in with Boarder Account</span>
                            </button>
                        </div>
                    </div>

                    <!-- Footers matching reference -->
                    <div class="mt-6 pt-2 text-center text-xs text-neutral-500 space-y-1.5">
                        <div>
                            <span class="text-neutral-400">Forgot your password?</span>
                            <span class="text-neutral-600 font-medium ml-1">Contact House Administrator</span>
                        </div>
                        <div>
                            <span class="text-neutral-400">Need resident access?</span>
                            <span class="text-blue-600 font-semibold ml-1">Register at Front Desk</span>
                        </div>
                    </div>
                </div>

                <!-- ======================================================= -->
                <!-- RIGHT COLUMN: Log in with QR Code (Matches Reference)   -->
                <!-- ======================================================= -->
                <div class="p-8 sm:p-10 lg:p-11 flex flex-col items-center justify-center text-center bg-white border-t md:border-t-0 md:border-l border-neutral-200" id="qr-column">
                    <div class="w-full max-w-xs flex flex-col items-center">

                        <!-- Prominent QR Code Box (Matches Reference Image) -->
                        <div class="p-4 bg-white rounded-2xl border border-neutral-200/80 shadow-xs inline-block transition-transform hover:scale-102" id="qr-box-wrapper" title="Scan with your phone to open RJM Boardinghouse">
                            <div id="qrcode-target" class="flex items-center justify-center" style="width: 196px; height: 196px; min-width: 196px; min-height: 196px;">
                                <!-- Fallback image if JS is disabled -->
                                <noscript>
                                    <img src="https://api.qrserver.com/v1/create-qr-code/?size=196x196&data=<?= urlencode($defaultMobileUrl) ?>" alt="QR Code" width="196" height="196" />
                                </noscript>
                            </div>
                        </div>

                        <!-- Title & Subtitle (Matches Reference Image) -->
                        <h2 class="text-2xl font-bold text-neutral-900 tracking-tight mt-6 mb-1.5" style="font-size: 1.5rem;">
                            Log in with QR code
                        </h2>
                        <p class="text-neutral-500 text-sm max-w-xs leading-relaxed mb-4">
                            Scan this with our App to log in instantly
                        </p>

                        <!-- Local Network Address Pill with Copy Tool -->
                        <div class="w-full flex items-center justify-between bg-neutral-50 border border-neutral-200 rounded-lg px-3 py-1.5 text-xs text-neutral-600 font-mono mt-1">
                            <span id="active-url-display" class="truncate select-all text-[11px]" title="<?= htmlspecialchars($defaultMobileUrl) ?>">
                                <?= htmlspecialchars($defaultMobileUrl) ?>
                            </span>
                            <button type="button"
                                    id="copy-url-btn"
                                    class="ml-2 text-neutral-500 hover:text-neutral-900 font-sans font-semibold text-[11px] px-2 py-0.5 rounded hover:bg-neutral-200 transition-colors flex-shrink-0 cursor-pointer"
                                    title="Copy link to clipboard">
                                Copy
                            </button>
                        </div>
                        <span id="copy-feedback" class="text-[11px] text-emerald-600 font-semibold opacity-0 transition-opacity mt-1">
                            ✓ Copied to clipboard!
                        </span>

                        <!-- Mobile Tips Badges -->
                        <div class="mt-4 flex items-center justify-center gap-3 text-[11px] text-neutral-400">
                            <span class="inline-flex items-center gap-1">
                                <span style="width:5px; height:5px; border-radius:50%; background:#22c55e;"></span>
                                <span>Local Wi-Fi Network</span>
                            </span>
                            <span>&middot;</span>
                            <a href="<?= htmlspecialchars($defaultMobileUrl) ?>" target="_blank" rel="noopener" class="text-blue-600 hover:underline font-medium">
                                Open mobile preview ↗
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Interactive Client-side Script: QR Code Generation + Login Validation -->
<script>
document.addEventListener("DOMContentLoaded", function () {
    const targetUrl = <?= json_encode($defaultMobileUrl) ?>;

    // 1. Generate Crisp QR Code locally via vendored QRCode.js
    const qrContainer = document.getElementById("qrcode-target");
    if (qrContainer && typeof QRCode !== "undefined") {
        qrContainer.innerHTML = ""; // Clear fallback
        new QRCode(qrContainer, {
            text: targetUrl,
            width: 196,
            height: 196,
            colorDark: "#0f172a",
            colorLight: "#ffffff",
            correctLevel: QRCode.CorrectLevel.M
        });
    }

    // 2. Clipboard Copy Button
    const copyBtn = document.getElementById("copy-url-btn");
    const copyFeedback = document.getElementById("copy-feedback");
    if (copyBtn) {
        copyBtn.addEventListener("click", function () {
            navigator.clipboard.writeText(targetUrl).then(function () {
                if (copyFeedback) {
                    copyFeedback.style.opacity = "1";
                    setTimeout(function () {
                        copyFeedback.style.opacity = "0";
                    }, 2200);
                }
            }).catch(function () {
                const temp = document.createElement("input");
                temp.value = targetUrl;
                document.body.appendChild(temp);
                temp.select();
                document.execCommand("copy");
                document.body.removeChild(temp);
                if (copyFeedback) {
                    copyFeedback.style.opacity = "1";
                    setTimeout(function () {
                        copyFeedback.style.opacity = "0";
                    }, 2200);
                }
            });
        });
    }

    // 3. Quick-fill credentials chips for testing
    const chips = document.querySelectorAll(".quick-account-chip");
    const emailInput = document.getElementById("login-email");
    const passInput = document.getElementById("login-password");
    chips.forEach(function (chip) {
        chip.addEventListener("click", function () {
            const em = this.getAttribute("data-email");
            const pw = this.getAttribute("data-pass");
            if (emailInput && passInput) {
                emailInput.value = em;
                passInput.value = pw;
                passInput.focus();
            }
        });
    });

    // 4. Password show/hide toggle
    const toggle = document.getElementById('toggle-password');
    const eyeOpen = document.getElementById('eye-open');
    const eyeClosed = document.getElementById('eye-closed');

    if (toggle && passInput) {
        toggle.addEventListener('click', function () {
            const isPassword = passInput.type === 'password';
            passInput.type = isPassword ? 'text' : 'password';
            eyeOpen.classList.toggle('hidden', isPassword);
            eyeClosed.classList.toggle('hidden', !isPassword);
            toggle.setAttribute('aria-label', isPassword ? 'Hide password' : 'Show password');
        });
    }

    // 5. Client-side validation
    const emailError = document.getElementById('email-error');
    const passwordError = document.getElementById('password-error');
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    function setEmailError(msg) {
        if (!emailError || !emailInput) return;
        if (msg) {
            emailError.textContent = msg;
            emailError.classList.remove('hidden');
            emailInput.classList.add('border-error');
            emailInput.setAttribute('aria-invalid', 'true');
        } else {
            emailError.classList.add('hidden');
            emailError.textContent = '';
            emailInput.classList.remove('border-error');
            emailInput.removeAttribute('aria-invalid');
        }
    }

    function setPasswordError(msg) {
        if (!passwordError || !passInput) return;
        if (msg) {
            passwordError.textContent = msg;
            passwordError.classList.remove('hidden');
            passInput.classList.add('border-error');
            passInput.setAttribute('aria-invalid', 'true');
        } else {
            passwordError.classList.add('hidden');
            passwordError.textContent = '';
            passInput.classList.remove('border-error');
            passInput.removeAttribute('aria-invalid');
        }
    }

    if (emailInput) {
        emailInput.addEventListener('blur', function () {
            const val = emailInput.value.trim();
            if (!val) {
                setEmailError('Email address is required.');
            } else if (!emailRegex.test(val)) {
                setEmailError('Please enter a valid email address.');
            } else {
                setEmailError('');
            }
        });

        emailInput.addEventListener('input', function () {
            if (emailError && !emailError.classList.contains('hidden')) {
                setEmailError('');
            }
        });
    }

    if (passInput) {
        passInput.addEventListener('blur', function () {
            const val = passInput.value;
            if (!val) {
                setPasswordError('Password is required.');
            } else {
                setPasswordError('');
            }
        });

        passInput.addEventListener('input', function () {
            if (passwordError && !passwordError.classList.contains('hidden')) {
                setPasswordError('');
            }
        });
    }

    const form = document.getElementById('login-form');
    if (form) {
        form.addEventListener('submit', function (e) {
            let valid = true;
            const emailVal = emailInput ? emailInput.value.trim() : '';
            const passVal = passInput ? passInput.value : '';

            if (!emailVal || !emailRegex.test(emailVal)) {
                setEmailError(emailVal ? 'Please enter a valid email address.' : 'Email address is required.');
                valid = false;
            }
            if (!passVal) {
                setPasswordError('Password is required.');
                valid = false;
            }
            if (!valid) {
                e.preventDefault();
                if (!emailVal || !emailRegex.test(emailVal)) {
                    emailInput && emailInput.focus();
                } else {
                    passInput && passInput.focus();
                }
            }
        });
    }

    // 6. GSAP Entrance Animation for the Modal Box
    if (window.gsap) {
        gsap.from("#login-modal-box", {
            opacity: 0,
            scale: 0.96,
            y: 20,
            duration: 0.5,
            ease: "power2.out"
        });
    }
});
</script>

<?php
$content = ob_get_clean();
require __DIR__ . '/layout.php';
